### ISSUE TITLE
Add a description for codacy-orbs

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-orbs#21]
The description given here is shown in Circleci Registry
https://github.com/codacy/codacy-orbs/blob/57651797bf4d33a7df68a1e5ce336e7a9afc61f3/src/%40orb.yml#L4

**Comment by jrcamelo** [comment]
This was fixed by #22

**Comment by lolgab** [comment]
Thank you for the reminder @jrcamelo
I'm closing this. Fixed by #22
